# Generated by Django 4.2.6 on 2023-11-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatusers',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
