# Generated by Django 4.2.6 on 2023-11-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatusers_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatusers',
            name='updated',
        ),
    ]
