# Generated by Django 4.2.6 on 2023-11-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_chatusers_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusers',
            name='name',
            field=models.CharField(default=models.CharField(max_length=150, unique=True), max_length=150, unique=True),
        ),
    ]
