# Generated by Django 4.2.6 on 2023-11-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_chatusers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatusers',
            name='name',
            field=models.CharField(default=models.CharField(max_length=150, unique=True), max_length=150),
        ),
    ]
